-- AI Generated Extra Quizzes Batch
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('high_3', 'english', '「spontaneous」の最も適切な日本語訳を選べ。', '["自発的な・自然発生的な","人為的な","慎重な","遅延した"]', 0, 2);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('high_3', 'english', '「reconcile」の意味として最も適したものはどれか？', '["和解させる・調和させる","否定する","拡張する","無視する"]', 0, 2);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('high_3', 'english', '仮定法過去完了の文構文「If I had known...」に続く正しい述語部分は？', '["I would have helped you.","I will help you.","I would help you.","I help you."]', 0, 2);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('high_3', 'social_studies', '1789年に勃発し、人権宣言が採択された市民革命はどれか？', '["フランス革命","アメリカ独立革命","名誉革命","清教徒革命"]', 0, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('high_3', 'social_studies', '国際連合安全保障理事会の常任理事国（5カ国）に含まれない国はどれか？', '["ドイツ","フランス","イギリス","中国"]', 0, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('high_3', 'social_studies', '日本国憲法において「基本的人権の尊重」「平和主義」と並ぶ三大原則の3つ目は？', '["国権の最高機関","主権在民（国政主権）","三権分立","地方自治"]', 1, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('high_3', 'science', 'アボガドロ定数（約6.02×10^23 /mol）が表す物質量は何か？', '["1 molに含まれる粒子数","1 Lの質量","1 kgの原子数","気体の1気圧での体積"]', 0, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('high_3', 'science', 'DNAの塩基配列において、アデニン（A）と水素結合で相補的に対をなす塩基は？', '["チミン（T）","シトシン（C）","グアニン（G）","ウラシル（U）"]', 0, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('junior_1', 'english', '「私は日曜日に図書館に行きます」の正しい英文はどれ？', '["I go to the library on Sunday.","I am go to the library on Sunday.","I going to the library on Sunday.","I went to library at Sunday."]', 0, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('junior_1', 'english', '「These are my books.」を単数形「これ（この本）」にする文章は？', '["This is my book.","That is my book.","This are my book.","These is my book."]', 0, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('junior_1', 'social_studies', '世界で最も面積が大きい大陸はどれか？', '["ユーラシア大陸","アフリカ大陸","北アメリカ大陸","オーストラリア大陸"]', 0, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('junior_1', 'social_studies', '日本の旧石器時代から縄文時代にかけて使われた、表面に縄目の文様がある土器は？', '["縄文土器","弥生土器","土師器","須恵器"]', 0, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('junior_1', 'science', '光が異なる物質の境界線で折れ曲がって進む現象を何というか？', '["光の屈折","光の反射","光の全反射","光の拡散"]', 0, 1);
INSERT INTO quiz_questions (grade_level, category, question_text, options_json, correct_index, difficulty) VALUES ('junior_1', 'science', '酸性の水溶液に青色リトマス紙をつけると、何色に変化するか？', '["赤色","青色（変化なし）","黄色","緑色"]', 0, 1);
